More comments

diff --git a/src/@orb.yml b/src/@orb.yml
--- a/src/@orb.yml
+++ b/src/@orb.yml
@@ -43,6 +43,13 @@ jobs:
           name: Authenticate with Pantheon's CLI using a machine token
           command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
 
+      # This section is a convuluted way of ensure that there are not git
+      # conflicts when pushing to Pantheon.
+      # Rather than pushing the history from GitHub/BitBucket to Pantheon,
+      # the Pantheon history is cloned to a tmp directory, changes are copied
+      # (rsync) to the Pantheon repo to be committed on top of history that can
+      # then push with no chance of a merge conflict (other than a race
+      # condition caused by a push going to Pantheon from elsewhere)
       - restore_cache:
             keys:
               - pantheon-repo-{{ .Branch }}
@@ -51,25 +58,27 @@ jobs:
           name: Checkout site repository from Pantheon
           command: |
             export PANTHEON_REPO_DIR="/tmp/pantheon_repo_for_$TERMINUS_SITE"
+            # Ensure that there's a Pantheon repo locally. If one was not
+            # restored from cache, clone it fresh.
             if [ ! -d "$PANTHEON_REPO_DIR/.git" ]; then
               mkdir $PANTHEON_REPO_DIR
-              git -C $PANTHEON_REPO_DIR init
-              git -C $PANTHEON_REPO_DIR remote add pantheon $(terminus connection:info $TERMINUS_SITE.dev --field=git_url)
-              git -C $PANTHEON_REPO_DIR remote -v
+              cd $PANTHEON_REPO_DIR
+              git init
+              git remote add pantheon $(terminus connection:info $TERMINUS_SITE.dev --field=git_url)
+              git remote -v
             fi
 
-            git -C $PANTHEON_REPO_DIR fetch pantheon
-            REMOTE_REF=$(git -C $PANTHEON_REPO_DIR ls-remote pantheon | grep "refs/heads/$TERMINUS_ENV$") || echo "hmm, assigning an empty var returns an error."
+            git fetch pantheon
+            REMOTE_REF_TO_ENV=$(git ls-remote pantheon | grep "refs/heads/$TERMINUS_ENV$") || echo "hmm, assigning an empty var returns an error."
 
-            if [ -n "$REMOTE_REF" ]; then
-              git -C $PANTHEON_REPO_DIR checkout $TERMINUS_ENV
-              git -C $PANTHEON_REPO_DIR pull
+            if [ -n "$REMOTE_REF_TO_ENV" ]; then
+              git checkout $TERMINUS_ENV
+              git pull
             else
-              git -C $PANTHEON_REPO_DIR checkout master
-              git -C $PANTHEON_REPO_DIR pull
-              git -C $PANTHEON_REPO_DIR checkout -b $TERMINUS_ENV
+              git checkout master
+              git pull
+              git checkout -b $TERMINUS_ENV
             fi
-
       - save_cache:
           key: pantheon-repo-{{ .Branch }}
           paths:
@@ -84,6 +93,7 @@ jobs:
           command: |
               export PANTHEON_REPO_DIR="/tmp/pantheon_repo_for_$TERMINUS_SITE"
               rsync -av --exclude='.git'  . $PANTHEON_REPO_DIR  --delete
+              # For easier debugging, show what files have changed.
               git -C $PANTHEON_REPO_DIR status
 
       - run:
@@ -93,19 +103,22 @@ jobs:
               # Create a new multidev site to test on
               terminus -n env:wake "$TERMINUS_SITE.dev"
               cd $PANTHEON_REPO_DIR
+              # This command will commit any changed files and push to Pantheon.
+              # New multidevs will be created as necessary.
               terminus -n build:env:create "$TERMINUS_SITE.live" "$TERMINUS_ENV" --yes --clone-content
       - run:
           name: Delete Multidev environments made for now-closed pull requests
           command: |
+            # Because this step is slow it should be run more than necessary.
             if [[ $CI_BRANCH != "master" ]] ; then
               exit 0
             fi
-            # Merge the multidev for the PR into the dev environment
-            terminus -n build:env:merge "$TERMINUS_SITE.$TERMINUS_ENV" --yes
             # Delete old multidev environments associated with a PR that has been
             # merged or closed.
             terminus -n build:env:delete:pr "$TERMINUS_SITE" --yes
 
+      # @todo, Check back with CircleCI DevRel team. They mentioned possibly
+      # adding a CircleCI-maintained Orb step to do this concept.
       - run:
           name: Copy environment variables to persist to workspace for use in subsequent jobs.
           command: cp $BASH_ENV bash_env.txt
